---
title: Stationery
---

Over the past six-plus years I've become interested in stationery. I feel happier when I use tools that I enjoy. I can look forward to taking notes in class with a nice notebook and well-made pen. I try to keep my collection small and avoid over-consumption. I recently went through my old stationery (felt pens, colored pencils, ballpoints, too many Sharpie colors, etc.) and donated a lot of it. The sections below detail my favorite pieces of stationery.

More and more often I take notes on paper. I used to be averse to the idea mostly due to concerns of organization and security, but nothing beats the feeling of showing up to a lecture with just a notebook and pen. I also find it easier to stay focused without my computer in front of me.
-----

* Fountain Pens
 |--------------------------+-----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
 | Pen                      | Nib       | Rating | Commentary                                                                                                                                                                                                                                                                                                         |
 |--------------------------+-----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
 | Diamond Medal            | 14k #3    | 7/10   | I love how thin the grip and light the body on this pen is. The nib feels amazing to write with, it has some feedback while still being smooth. The filling mechanism sucks, and I dropped it and cracked the barrel. I'd like to put the nib in another pen.                                                      |
 | Waterman Carene          | F         | 8/10   | This is a really elegant and well-made pen. I'm not the biggest fan of hooded  nibs but I enjoy this one. It writes beautifully and never has any dry starts or skipping. It is on the heavier side. I've been using it alone for notes for a month and have enjoyed carrying it.                                  |
 | Blue Esterbrook J        | #9668     | 5/10   | The fatter cousin of the LJ. I really wanted to like this and use it a lot but I don't find myself with it often. I think the nib is a little hard and broad for my taste and it doesn't suit me as well as the LJ so I avoid it.                                                                                  |
 | Copper Esterbrook LJ     | #9556     | 9/10   | I think this pen is one of the greatest of all time. From the ink capacity, to the size, to the nib I have, is just excellent. And it really looks great, too. I used this almost exclusively for notes and exams in class for a long time. I'm always amazed that an 80+ year old pen still works so wonderfully. |
 | Kaweco Sport             | B         | 6.5/10 | A solid, small pen. I am surprised by how much I like carrying it. It writes well and holds enough ink for a week's travel. It does strike me as fragile at times.                                                                                                                                                 |
 | Parker Challenger (1940) | Fine Flex | 7/10   | This pen was my grandfather's. I love the small size and the button filler is neat. I don't use it now that I have more of my own pens. This was the first fountain pen I tried.                                                                                                                                   |
 | TWSBI Eco                | M         | 4/10   | This was a good beginner pen. I don't like the way it feels in the hand anymore and it writes okay. I got it because I wanted a lot of ink capacity but I never needed it that badly.                                                                                                                       |
 |--------------------------+-----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

Broadly, I prefer vintage pens to modern ones. I think that vintage have better build quality and were designed with extended writing in mind. Fountain pens are now a luxury item which leads to different priorities. My vintage pens have smaller grips and are lighter which I find are two things that make them more comfortable to use for extended periods of time. On the other hand, they can be more finnickey or suffer from age-related faults.
 
* Inks
My go-to ink is Waterman Mysterious Blue. It's good-looking, inexpensive, and safe for all pens. I own a few more inks that I use every so often, but more often than not I just refill with Mysterious Blue.

* Mechanical Pencils

I own a GraphGear 1000. It was a gift from a friend. It's a good beater pencil to use in a variety of situations. I keep it on my desk. The greatest mechanical pencils ever made were the Alvin DraftMatic series. I bought them when I saw they were not being made anymore. Recently, production was restarted, but I don't think they are exactly the same. The DraftMatics feature a very rough grip which I like. I also own a Pentel Smash which features an unusual grip. It's a nice pencil to have around.

* Regular Pens

I haven't bought a box of regular pens in many years. I still have a few BIC Gelocity pens left which I love. They write really nicely --- smooth, black ink that lasts a long time. Only con is the dry-time is a bit long.

I do own and carry with me a Caran d'Ache 849 ballpoint pen. This is an excellent pen --- it's one of the smoothest ballpoints out there and lasts a really long time. It is also an elegant pen so serves as a good backup or just for switching things up.

* Notebooks and Paper

I am a big fan of Life A5 notebooks. The paper is awesome and I like the overall feel of the notebook. I got one for a dollar at a thrift store. Another good one are the Oasis notebooks. I like the ruled-grid combo design. I prefer the Oasis notebooks for technical notetaking (e.g. math and science) and the Life for other sorts of notes. The Oasis has smoother, slicker paper, whereas the Life's paper feels a tiny bit more natural and rough, and ink appears better on it.

I journal with a Midori A5 grid notebook. The paper is nice and it has a lot of pages, making it a suitable journal.

I prefer softcover notebooks to hardcover ones. Notebooks with stitching are better than ones without. A5 is my preferred size.
